<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>/home/kyu/Downloads/unzip/MelonLoader/net6/MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>/home/kyu/programmin/MelonLoader/Dependencies/SupportModules/Mono/Libs/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>/home/kyu/.local/share/Steam/steamapps/common/Wordatro! Demo/Wordatro!_Data/Managed/Assembly-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HarmonyX" Version="2.13.1" />
  </ItemGroup>

</Project>
